### ISSUE TITLE
Does not remove comments beginning with /*!

### ISSUE THREAD

**Issue by stephanepechard** [ben-eb/gulp-cssnano#27] opened 2016-01-27 10:22 UTC
Hi,

cssnano does not remove comments formatted like the first one in the `angular-material.css` file. Note the extra `!` after the `/*`:

    /*!
     * Angular Material Design
     * https://github.com/angular/material
     * @license MIT
     * v1.0.2
    */

Remove the extra `!` and the comment is removed as wanted.

The funny thing is that they provide their own `angular-material.min.css` (which I don't use) and it also contains the whole comment at the beginning of the file. [They use](https://github.com/angular/material/blob/master/gulp/tasks/build-scss.js#L12) the `gulp-minify-css` package.

**Comment by ben-eb** [comment] 2016-01-27 11:30
Duplicate of https://github.com/ben-eb/cssnano/issues/102.

**Closed by ben-eb** 2016-01-27 11:30 UTC

**Comment by DeadcatDev** [comment] 2016-02-01 18:02
Can't it be option in gulp-cssnano? Do we really need to require another lib just for full comments trim? Please buddy, do us a favor :+1: :)

**Comment by ben-eb** [comment] 2016-02-01 18:21
@DeadcatDev The options object is passed through :wink:

```js
var gulp = require('gulp');
var cssnano = require('gulp-cssnano');

gulp.task('default', function () {
    return gulp.src('./main.css')
        .pipe(cssnano({
            discardComments: {removeAll: true}
        }))
        .pipe(gulp.dest('./out'));
});
```

**Comment by DeadcatDev** [comment] 2016-02-02 08:58
Thank you! :+1:

**Comment by eMahtab** [comment] 2016-11-06 02:36
Thanks for this
