### ISSUE TITLE
-ms-transform being stripped

### ISSUE THREAD

**Issue by miraclemaker** [ben-eb/gulp-cssnano#59] opened 2016-10-04 12:04 UTC
With gulp-cssnano version 2.1.2

GULP TASK:
gulp.task('testcss', function () {
	return gulp.src('test.css')
        .pipe(plumber())
		.pipe(cssnano())
		.pipe(gulp.dest('../'));
});

INPUT CSS:
body {
    -webkit-transform: skewY(10deg);
    -ms-transform: skewY(10deg);
    transform: skewY(10deg);
}

EXPECTED OUTPUT:
body{-webkit-transform:skewY(10deg);-ms-transform:skewY(10deg);transform:skewY(10deg)}

ACTUAL OUTPUT:
body{-webkit-transform:skewY(10deg);transform:skewY(10deg)}

I have found other -ms-transform statements like translate get through ok so maybe this is something specific to skew.

Thanks.

**Comment by ben-eb** [comment] 2016-10-08 10:08
Hi,

This is a duplicate of https://github.com/ben-eb/cssnano/issues/176.

**Closed by ben-eb** 2016-10-08 10:08 UTC
