### ISSUE TITLE
errors when the css files containing 'z-index'

### ISSUE THREAD

**Issue by wormcc** [ben-eb/gulp-cssnano#22] opened 2016-01-23 02:27 UTC
when i use cssnano to compress the css files containing 'z-index:100', it transforms 'z-index:100' into 'z-index:1',but the gulp-minify-css works fine.

**Comment by ben-eb** [comment] 2016-01-23 09:39
Duplicate of https://github.com/ben-eb/gulp-cssnano/issues/14.

**Closed by ben-eb** 2016-01-23 09:39 UTC
