### ISSUE TITLE
Gulp not finishing task

### ISSUE THREAD

**Issue by hayo1985** [ben-eb/gulp-cssnano#35] opened 2016-02-11 11:05 UTC
I am using cssnano 2.0.1 but my minification task doesn't finish:

[12:02:48] Starting 'less-compile'...
[12:02:48] Finished 'less-compile' after 378 ms
[12:02:48] Starting 'css-minify'...
Process terminated with code 0.

This is the code i am using. When i remove the .pipe(cssnano()) the task finishes just not minified.

```
 var clientSrcRootName = 'wwwroot';
    var client = './' + clientSrcRootName + '/';
    var clientStyles = path.join(client, 'styles');

gulp.task('less-compile', function () {
    return gulp.src(config.less)
        .pipe(sourcemaps.init())
        .pipe(less({}))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(config.clientStyles));
});
gulp.task('css-minify', ['less-compile'], function () {
    return gulp.src(config.cssOnly)
        .pipe(cssnano())
        .pipe(rename(function (path) {
            path.extname = '.min' + path.extname;
        }))
        .pipe(gulp.dest(config.clientStyles));
});
```

I have also tried the following code from another example:
```
gulp.task('less', function () {
    var cssnano = require('gulp-cssnano');
    var postcss = require('gulp-postcss');
    var cssnext = require('postcss-cssnext');
    var gradientfixer = require('postcss-gradientfixer');
    var processors = [
        gradientfixer,
        cssnext
    ];
    var css = gulp.src(config.less)
      .pipe(sourcemaps.init())
      .pipe(less({}))
      .pipe(postcss(processors));
    
    var min = css.pipe(clone())
      .pipe(cssnano({ discardComments: { removeAll: true } }))
      .pipe(rename(function (path) {
          path.extname = '.min' + path.extname;
      }));

    return merge(css, min)
      .pipe(sourcemaps.write('./'))
      .pipe(gulp.dest(config.clientStyles));
});
```

However same result:
[12:06:31] Starting 'less'...
Process terminated with code 0.

**Comment by ben-eb** [comment] 2016-02-11 14:19
Can you try reinstalling? I've released a couple of patches that fixed some crashes caused by the recent update to postcss-discard-comments.

**Comment by mewdriller** [comment] 2016-02-16 21:30
I'm seeing this behavior on v2.1.1. From debugging the situation with `on('data')` logging, it gets the the `cssnano` call and exits without an error being thrown.

If it helps track things down, using the CLI works properly. For reference, the output of `cssnano -v` is `cssnano v3.5.2 (cli v1.0.3)`.

**Comment by JeremyEnglert** [comment] 2016-02-20 00:10
Potentially related: https://github.com/ben-eb/gulp-cssnano/issues/35

**Comment by kilianc** [comment] 2016-02-29 07:45
+1 as well posted my code on #38

**Comment by ben-eb** [comment] 2016-04-18 21:25
This is resolved in https://github.com/ben-eb/gulp-cssnano/commit/67795f65cbff99e66e3ecceac56ce274233233f0. 🎉

**Closed by ben-eb** 2016-04-18 21:25 UTC
