### ISSUE TITLE
minified style is wrong

### ISSUE THREAD

**Issue by jylzs369** [ben-eb/gulp-cssnano#84] opened 2017-02-05 07:23 UTC
I set a rule **z-index: 6000** in my css file,
but minified result is **z-index:2**.
what's wrong here?

**Comment by ben-eb** [comment] 2017-02-06 00:05
Duplicate of https://github.com/ben-eb/gulp-cssnano/issues/14. 😄

**Closed by ben-eb** 2017-02-06 00:05 UTC

**Comment by jylzs369** [comment] 2017-02-06 01:55
thx!!
