### ISSUE TITLE
minifying z-index results in invallid value

### ISSUE THREAD

**Issue by nickheijmink** [ben-eb/gulp-cssnano#56] opened 2016-09-15 13:22 UTC
When a piece of css is minified that contains a z-index then only the first digit is outputted
so for example:

.stylex{
 z-index: 123;
}

results into

.stylex{ z-index:1;}

**Comment by ben-eb** [comment] 2016-09-15 16:44
Duplicate of https://github.com/ben-eb/gulp-cssnano/issues/14.

**Closed by ben-eb** 2016-09-15 16:44 UTC
